package.json, src/components/Feedback/ConfirmationPopup.stories.tsx, src/components/Feedback/ConfirmationPopup.tsx, src/components/Inputs/Select/OptionDrawer.stories.tsx
- Added `width` prop to confirmation popup
- Also updated stories for
- ConfirmationPopup
- OptionDrawer
=> Added width prop to confirmationpopup

package.json, src/components/Inputs/ContentMenu.tsx
Also switched openendParents to be a ref instead of state since we don't need it to be state
=> :bug: Fixed ContentMenu throwing keys error

package.json, src/utils/auth_environment.ts
=> Fix return type of getEnvironmentName util

package.json, src/components/Feedback/AnimatedCheckmark.stories.tsx, src/components/Feedback/AnimatedCheckmark.test.tsx, src/components/Feedback/AnimatedCheckmark.tsx, src/components/Feedback/SelectField/ChangingField.tsx, src/components/Feedback/SelectField/SelectField.tsx, src/components/Navigation/SideBar/SideBar.tsx, src/components/Navigation/SideBar/ToggleOpen.tsx, src/components/index.ts, src/utils/favicon.stories.tsx, src/utils/map.stories.tsx, src/utils/size.stories.tsx, src/utils/sort.stories.tsx, src/utils/string.stories.tsx, src/utils/url.stories.tsx
- Exported application icons
- Added AnimatedCheckmark component so we can use it wherever
- Fixed height of SideBar/ToggleOpen LargeButton
=> Added AnimatedCheckmark component and exported app icons

Dockerfile
hopefully this will appease radix
=> :bug: attempt to use pid instead to set proper permission

config/config_files/nginx.conf
added new line, also included security headers on html location specifically, PWEX needs this, unsure about other apps
=> :art: update nginx conf

config/config_files/nginx.conf
hopefully last PR on this for a while 😅
=> :bug: include securityheaders from conf.d folder

.yarnrc.yml, config/config_files/.yarnrc.yml, config/config_files/Dockerfile
=> :lock: disable scripts when running yarn

package.json, src/components/Navigation/SideBar/CreateItem.tsx, src/components/Navigation/SideBar/CreateItem.utils.ts, src/components/Navigation/SideBar/MenuItem.test.tsx, src/components/Navigation/SideBar/MenuItem.tsx, src/components/Navigation/SideBar/MenuItem.utils.ts, src/components/Navigation/SideBar/SideBar.stories.tsx, src/components/Navigation/SideBar/SideBar.test.tsx, src/components/Navigation/SideBar/SideBar.tsx, src/components/Navigation/SideBar/SideBar.types.ts, src/components/Navigation/SideBar/SideBar.utils.ts, src/components/Navigation/SideBar/ToggleOpen.tsx
To be used on new admin pages in pwex:
=> Dark mode for sidebar

src/components/Navigation/TopBar/Help/Help.test.tsx, src/components/Navigation/TopBar/Help/ReleaseNotesDialog/Filters/FilterHeader.styles.ts, src/components/Navigation/TopBar/Help/ReleaseNotesDialog/Filters/FilterHeader.tsx, src/providers/providers.stories.tsx
=> :sparkles: added close button inside modal

SECURITY.md
- Added SECURITY.md from [template](https://github.com/equinor/it-professional-network/blob/master/doc/SECURITY-template.md)
=> docs: :memo: Added Security.md

src/components/index.ts
Forgot to add new Icons to index file in last PR
=> :art: Added new icons to index

package.json
Forgot to bump version number when added icons to index... .
=> :bookmark: 5.5.2

package.json, src/api/services/ReleaseNotesService.ts, src/components/Navigation/TopBar/Help/Help.test.tsx, src/components/Navigation/TopBar/Help/ReleaseNotesDialog/ReleasePosts/ReleasePosts.test.tsx, src/components/Navigation/TopBar/Help/ReleaseNotesDialog/ReleasePosts/ReleasePosts.tsx, src/components/Navigation/TopBar/Help/ReleaseNotesDialog/ReleasePosts/hooks/useTokenReleaseNote.ts, src/components/Navigation/TopBar/Help/ReleaseNotesDialog/TextContent.test.tsx, src/components/Navigation/TopBar/Help/ReleaseNotesDialog/TextContent.tsx
Add token to IMG src in TextContent to show image in release notes. 
AB#441219
=> :sparkles: Add read token to release note to show image

package.json
Forgot to bump version on previous PR
=> :bookmark: 5.6.3

.gitignore, .idea/.gitignore, .idea/amplify-components.iml, .idea/inspectionProfiles/Project_Default.xml, .idea/jsLinters/eslint.xml, .idea/modules.xml, .idea/prettier.xml, .idea/vcs.xml, .run/brute-coverage.run.xml, .run/build-and-use.run.xml, .run/build-components.run.xml, .run/build-storybook.run.xml, .run/lint_fix.run.xml, .run/pretty.run.xml, .run/pretty_fix.run.xml, .run/setup.run.xml, config/config_files/.gitignore, package.json, src/components/Navigation/PageWithTitle.test.tsx, src/components/Navigation/PageWithTitle.tsx, src/components/Navigation/SideBar/SideBar.tsx, src/components/index.ts
Created new component which is to be used where we want a page to have a custom title, such as 'Search - PWEX'
[AB#455981](https://dev.azure.com/Equinor/4319082b-29ba-4111-a20b-c04f55c7e7c6/_workitems/edit/455981)
=> PageWithTilte wrapper component

config/config_files/.lintstagedrc.yaml
Pre commit wasn't working when calling eslint/prettier directly
=> Update .lintstagedrc.yaml to use NPM scripts

package.json, src/components/Navigation/TopBar/Help/ReleaseNotesDialog/ReleasePosts/ReleasePost.tsx, src/components/Navigation/TopBar/Help/ReleaseNotesDialog/ReleasePosts/ReleasePosts.test.tsx, src/components/Navigation/TopBar/Help/ReleaseNotesDialog/ReleasePosts/ReleasePosts.tsx
=> 🐛 Wrong sorting within month of release notes

config/config_files/nginx.conf, proxy/nginx.conf
The env-config file is so small that the performance hit is negligible
AB#453137
=> :wrench: do not cache env-config.js

config/config_files/setupLocalhost.mjs, package-lock.json, package.json
=> Fixing setupLocalhost.mjs script

package.json, src/components/Inputs/RichTextEditor/RichTextEditor.styles.ts, src/components/Inputs/RichTextEditor/custom-extensions/ExtendedImage.ts
This is the last one today, promise 🤞🏻
=> Fix height and plugin crash - RichTextEditor

package.json, src/components/Navigation/TopBar/Help/ReleaseNotesDialog/ReleasePosts/ReleasePosts.tsx, src/utils/releaseNotes.test.ts, src/utils/releaseNotes.ts
=> 🐛 Release notes months is sorted the wrong way

package.json, src/components/DataDisplay/RichTextDisplay.test.tsx, src/components/DataDisplay/RichTextDisplay.tsx, src/components/Inputs/RichTextEditor/RichTextEditor.styles.ts
Added a new prop to the RichTextDisplay component so we can send in read tokens on the fly
=> RichTextDisplay - imageReadToken prop

package-lock.json, package.json, src/components/Feedback/SelectField/ChangingField.tsx, src/hooks/index.ts, src/hooks/useFakeProgress.test.tsx, src/hooks/useFakeProgress.ts
- [AB#465682](https://dev.azure.com/Equinor/4319082b-29ba-4111-a20b-c04f55c7e7c6/_workitems/edit/465682)
- [AB#465683](https://dev.azure.com/Equinor/4319082b-29ba-4111-a20b-c04f55c7e7c6/_workitems/edit/465683)
- [AB#465684](https://dev.azure.com/Equinor/4319082b-29ba-4111-a20b-c04f55c7e7c6/_workitems/edit/465684)
=> Created useFakeProgress hook

package-lock.json, package.json, src/providers/AuthProvider/AuthProviderInner.tsx, src/utils/auth_environment.ts
I have not tested that this works, I don't know of a good way to test this so if anyone has any good ideas I am all ears.
=> :bug: avoid silent auth crashes

.idea/inspectionProfiles/profiles_settings.xml, package.json, src/components/Inputs/ComboBox/ComboBox.stories.tsx, src/components/Inputs/ComboBox/ComboBox.styles.ts, src/components/Inputs/ComboBox/ComboBox.test.tsx, src/components/Inputs/ComboBox/ComboBox.tsx, src/components/Inputs/ComboBox/ComboBox.types.ts, src/components/Inputs/RichTextEditor/RichTextEditor.styles.ts
Userstory
- [AB#473192](https://dev.azure.com/Equinor/4319082b-29ba-4111-a20b-c04f55c7e7c6/_workitems/edit/473192)
- [AB#478092](https://dev.azure.com/Equinor/4319082b-29ba-4111-a20b-c04f55c7e7c6/_workitems/edit/478092)
Task:
- [AB#479183](https://dev.azure.com/Equinor/4319082b-29ba-4111-a20b-c04f55c7e7c6/_workitems/edit/479183)
- [AB#479200](https://dev.azure.com/Equinor/4319082b-29ba-4111-a20b-c04f55c7e7c6/_workitems/edit/479200)
=> Add clearable functionality to combo box

package.json, src/components/DataDisplay/RichTextDisplay.tsx, src/components/Inputs/RichTextEditor/RichTextEditor.styles.ts
[AB#470080](https://dev.azure.com/Equinor/DPP%20Upscaling%20of%20digital%20solutions/_workitems/edit/470080)
=> 🎨Add lightBackground prop to rich text editor.

package.json, src/components/DataDisplay/RichTextDisplay.test.tsx, src/components/DataDisplay/RichTextDisplay.tsx, src/components/Inputs/RichTextEditor/RichTextEditor.styles.ts
[AB#470080](https://dev.azure.com/Equinor/DPP%20Upscaling%20of%20digital%20solutions/_workitems/edit/470080)
=> 🎨make padding configurable

package.json, src/components/Inputs/ComboBox/ComboBox.styles.ts, src/components/Inputs/ComboBox/ComboBox.test.tsx, src/constants/colors.ts, src/constants/index.ts, src/index.ts
[AB#482784](https://dev.azure.com/Equinor/DPP%20Upscaling%20of%20digital%20solutions/_workitems/edit/482784)
=> 💄 Introduce new color and use it in Combobox

package.json, src/components/Inputs/ComboBox/ComboBox.styles.ts
[AB#483716](https://dev.azure.com/Equinor/DPP%20Upscaling%20of%20digital%20solutions/_workitems/edit/483716)
=> 💄 Combobox styling issue

package-lock.json, package.json, src/components/Icons/ApplicationIcon/ApplicationIconBase.tsx, src/components/Navigation/TopBar/Account/Account.test.tsx, src/components/Navigation/TopBar/Account/Account.tsx, src/components/Navigation/TopBar/ApplicationDrawer/ApplicationDrawer.test.tsx, src/components/Navigation/TopBar/Guidelines/Guidelines.test.tsx, src/components/Navigation/TopBar/Guidelines/Guidelines.tsx, src/components/Navigation/TopBar/Guidelines/Section.tsx, src/components/Navigation/TopBar/Notifications/NotificationsInner.tsx, src/components/Navigation/TopBar/Resources/ResourceMenuItem.tsx, src/components/Navigation/TopBar/Resources/Resources.test.tsx, src/components/Navigation/TopBar/Resources/Resources.tsx, src/components/Navigation/TopBar/Settings.test.tsx, src/components/Navigation/TopBar/Settings.tsx, src/components/Navigation/TopBar/TopBarMenu.tsx
- Move out report bug and suggest idea to first click in Resources. 
- Update styling after updated design 
https://www.figma.com/file/fk8AI59x5HqPCBg4Nemlkl/%F0%9F%92%A0-Component-Library---Amplify?type=design&node-id=3587-50019&mode=design&t=jzfgYxzVaUwZCs6y-0
[AB#461428](https://dev.azure.com/Equinor/4319082b-29ba-4111-a20b-c04f55c7e7c6/_workitems/edit/461428)
=> 💄 Update styling for top bar 

package.json, src/components/Inputs/ComboBox/ComboBox.styles.ts
[AB#468530](https://dev.azure.com/Equinor/DPP%20Upscaling%20of%20digital%20solutions/_workitems/edit/468530)
=> 💄 Remove underline when Combobox is disabled

package-lock.json, package.json
=> Fix - Bump version number 

package-lock.json, package.json, src/components/Navigation/TopBar/ApplicationDrawer/ApplicationDrawer.styles.ts, src/components/Navigation/TopBar/ApplicationDrawer/ApplicationDrawer.test.tsx, src/components/Navigation/TopBar/ApplicationDrawer/ApplicationDrawer.tsx, src/components/Navigation/TopBar/Guidelines/Section.tsx, src/components/Navigation/TopBar/Resources/Resources.test.tsx, src/components/Navigation/TopBar/Settings.tsx
Small changes in design after design feedback and increased timeout for test that are sometimes failing in code coverage
=> 🎨 Small changes in spacings size and increase timeout for tes 

package-lock.json, package.json, src/components/Navigation/SideBar/CreateItem.styles.ts, src/components/Navigation/SideBar/CreateItem.tsx
=> 🐛 Wrong button style on side bar create item

package-lock.json, package.json, src/components/Navigation/SideBar/CreateItem.styles.ts, src/components/Navigation/SideBar/MenuItem.styles.ts, src/components/Navigation/SideBar/ToggleOpen.styles.ts, src/components/Navigation/TopBar/Account/Account.styles.ts, src/components/Navigation/TopBar/Account/Account.tsx, src/components/Navigation/TopBar/TopBar.styles.ts, src/components/Navigation/TopBar/TopBar.test.tsx, src/components/Navigation/TopBar/TopBar.tsx
Task: AB#489759
UserStory: AB#448593
=> 💄 Fix focus styles in TopBar and app logo size back to 32

package-lock.json, package.json, src/components/DataDisplay/Card/Card.docs.mdx, src/components/DataDisplay/Card/Card.stories.tsx, src/components/index.ts
Export this because I use in Dasha
=> Export Card component from Eds 

package-lock.json, package.json, src/components/Navigation/TableOfContents/TableOfContents.constants.ts, src/components/Navigation/TableOfContents/TableOfContents.stories.tsx, src/components/Navigation/TableOfContents/TableOfContents.styles.ts, src/components/Navigation/TableOfContents/TableOfContents.test.tsx, src/components/Navigation/TableOfContents/TableOfContents.tsx, src/components/Navigation/TableOfContents/TableOfContentsItem.tsx, src/providers/TableOfContentsProvider.test.tsx, src/providers/TableOfContentsProvider.tsx
Userstory
- [AB#490574](https://dev.azure.com/Equinor/4319082b-29ba-4111-a20b-c04f55c7e7c6/_workitems/edit/490574)
Tasks
- [AB#490729](https://dev.azure.com/Equinor/4319082b-29ba-4111-a20b-c04f55c7e7c6/_workitems/edit/490729)
- [AB#490730](https://dev.azure.com/Equinor/4319082b-29ba-4111-a20b-c04f55c7e7c6/_workitems/edit/490730)
- [AB#490731](https://dev.azure.com/Equinor/4319082b-29ba-4111-a20b-c04f55c7e7c6/_workitems/edit/490731)
=> TOC improvements

package-lock.json, package.json, src/providers/TableOfContentsProvider.test.tsx, src/providers/TableOfContentsProvider.tsx
[AB#493049](https://dev.azure.com/Equinor/DPP%20Upscaling%20of%20digital%20solutions/_workitems/edit/493049)
=> 🎨 Allow scrolling behaviour to be configured

package-lock.json, package.json, src/components/Navigation/TableOfContents/TableOfContents.styles.ts, src/components/Navigation/TableOfContents/TableOfContentsItem.tsx
[AB#493980](https://dev.azure.com/Equinor/DPP%20Upscaling%20of%20digital%20solutions/_workitems/edit/493980)
[AB#493055](https://dev.azure.com/Equinor/DPP%20Upscaling%20of%20digital%20solutions/_workitems/edit/493055)
=> 💄 Disabled font when count = 0

package-lock.json, package.json, src/components/DataDisplay/Badge/Badge.docs.mdx, src/components/DataDisplay/Badge/Badge.stories.tsx, src/components/DataDisplay/Badge/Badge.styles.tsx, src/components/DataDisplay/Badge/Badge.test.tsx, src/components/DataDisplay/Badge/Badge.tsx, src/components/Navigation/TableOfContents/TableOfContents.styles.ts, src/components/Navigation/TableOfContents/TableOfContentsItem.tsx, src/components/index.ts
[AB#493096](https://dev.azure.com/Equinor/DPP%20Upscaling%20of%20digital%20solutions/_workitems/edit/493096)
Also agreed with PC that the badge should be extracted.
=> ✨ Create and use Badge component

package-lock.json, package.json, src/components/DataDisplay/Chip/Chip.styles.tsx, src/components/DataDisplay/Chip/Chip.test.tsx, src/components/DataDisplay/Chip/Chip.tsx
Fix active and error variants according to -
https://www.figma.com/file/fk8AI59x5HqPCBg4Nemlkl/%F0%9F%92%A0-Component-Library---Amplify?type=design&node-id=2382-83653&mode=design&t=jQpoC2BZrY1ZhzL9-0
=> 💄 Fix active and error variants in chips

package-lock.json, package.json, src/components/Feedback/ConfirmationPopup.tsx
Need it for some changes in: 
[AB#489193](https://dev.azure.com/Equinor/DPP%20Upscaling%20of%20digital%20solutions/_workitems/edit/489193)
=> 💄 Make ConfirmationPopup dismissible

package.json, src/components/Feedback/ErrorPage/MissingAccesses.tsx
[AB#505007](https://dev.azure.com/Equinor/4319082b-29ba-4111-a20b-c04f55c7e7c6/_workitems/edit/505007)
=> :sparkles: Text prop and optional URL on MissingAccesses on ErrorPage

package-lock.json, package.json, src/hooks/useLocalStorage.ts
Need in [AB#498132](https://dev.azure.com/Equinor/DPP%20Upscaling%20of%20digital%20solutions/_workitems/edit/498132)
=> 🎨 UseLocalStorage use native setter

package-lock.json, package.json, src/providers/TableOfContentsProvider.tsx
[AB#506602](https://dev.azure.com/Equinor/Johan%20Sverdrup%20Digitalisation/_workitems/edit/506602)
=> 🐛 TableOfContent brakes navigation

package-lock.json, package.json, src/api/core/OpenAPI.ts
Fixes the issue with mocked tokens.
[AB#508251](https://dev.azure.com/Equinor/Johan%20Sverdrup%20Digitalisation/_workitems/edit/508251)
=> 🐛 Parse token safely

package-lock.json, package.json, src/components/Inputs/ComboBox/ComboBox.styles.ts, src/components/Inputs/ComboBox/ComboBox.test.tsx, src/components/Inputs/ComboBox/ComboBox.tsx, src/components/Inputs/ComboBox/ComboBoxMenu.tsx
[AB#510057](https://dev.azure.com/Equinor/DPP%20Upscaling%20of%20digital%20solutions/_workitems/edit/510057)
=> 💄 Use custom chip in combobox

package-lock.json, package.json, src/components/Inputs/Select/OptionDrawer.tsx
[AB#510983](https://dev.azure.com/Equinor/Johan%20Sverdrup%20Digitalisation/_workitems/edit/510983)
=> 🐛 OptionDrawer - Use the correct toggling arrows

.github/workflows/build.yaml, .github/workflows/build_storybook.yaml, .github/workflows/code_coverage.yaml, .github/workflows/lint.yaml, .github/workflows/npm_publish.yaml, .github/workflows/release.yaml, .github/workflows/test.yaml, config/config_files/workflows/build.yaml, config/config_files/workflows/build_docker.yaml, config/config_files/workflows/check_config.yaml, config/config_files/workflows/lint.yaml, config/config_files/workflows/release.yaml, config/config_files/workflows/test.yaml
=> Update github actions to newer version

.storybook/addons/GitHubSearchAddon/Panel.js, .storybook/addons/GitHubSearchAddon/constants.js, .storybook/addons/GitHubSearchAddon/manager.js, .storybook/main.js, Dockerfile, docker-compose.yaml, package-lock.json, package.json, proxy/nginx.conf, radixconfig.yaml, secrets.sh
Userstory:
- AB#517676
Tasks:
- AB#519818
- AB#519819
=> Check component usage storybook panel

.husky/pre-commit, .storybook/preview.tsx, package-lock.json, package.json, src/components/DataDisplay/DataCard.stories.tsx, src/components/DataDisplay/DataCard.tsx, src/components/DataDisplay/HeaderDrawer.stories.tsx, src/components/DataDisplay/HeaderDrawer.tsx, src/components/DataDisplay/Popover/Popover.stories.tsx, src/components/DataDisplay/Workflow/StatusChip.stories.tsx, src/components/DataDisplay/Workflow/StatusChip.tsx, src/components/DataDisplay/Workflow/WorkflowDescription.stories.tsx, src/components/DataDisplay/Workflow/WorkflowDescription.tsx, src/components/DataDisplay/Workflow/WorkflowStatusBar.stories.tsx, src/components/DataDisplay/Workflow/WorkflowStatusBar.tsx, src/components/Inputs/Label/Label.stories.tsx, src/components/index.ts
Userstories:
- AB#521183
- AB#521185
- AB#521187
- AB#521238
Tasks:
- AB#524908
- AB#524909
- AB#524912
- AB#524910
=> Deprecate components

.github/workflows/secret_scanning.yaml, config/config_files/workflows/secret_scanning.yaml, config/github_actions_list.txt
[AB#526166](https://dev.azure.com/Equinor/4319082b-29ba-4111-a20b-c04f55c7e7c6/_workitems/edit/526166)
=> :construction_worker: added secret scanning workflow

src/atoms/icons/map.ts, src/atoms/icons/other.ts, src/storybook/AmplifyIconPreview/AmplifyIconPreview.docs.mdx, src/storybook/AmplifyIconPreview/AmplifyIconPreview.stories.tsx
- [AB#509904](https://dev.azure.com/Equinor/4319082b-29ba-4111-a20b-c04f55c7e7c6/_workitems/edit/509904)
=> Amplify icons preview in storybook

src/atoms/hooks/useSelect.ts, src/molecules/Select/GroupedSelectMenu.tsx, src/molecules/Select/Select.styles.ts, src/molecules/Select/Select.tsx, src/molecules/Select/Select.types.ts, src/molecules/Select/SelectMenu.tsx, src/molecules/Select/SelectMenuItem.tsx
- [AB#522861](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/522861)
=> Make "hover state" persistent for select components

src/molecules/AnimatedCheckmark/AnimatedCheckmark.stories.tsx, src/molecules/AnimatedCheckmark/AnimatedCheckmark.styles.ts, src/molecules/AnimatedCheckmark/AnimatedCheckmark.test.tsx, src/molecules/AnimatedCheckmark/AnimatedCheckmark.tsx, src/molecules/AnimatedCheckmark/AnimatedCheckmark.utils.ts, src/organisms/TopBar/TransferToAppDialog.tsx
- [AB#512564](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/512564)
=> Animated checkmark - sizes

src/molecules/FullPageSpinner/FullPageSpinner.stories.tsx, src/molecules/FullPageSpinner/FullPageSpinner.test.tsx, src/molecules/Sieve/Sieve.tsx, src/molecules/Stepper/Step.tsx, src/organisms/TopBar/Resources/Feedback/ResponsePage/RequestStatus.tsx, src/providers/TableOfContentsProvider.tsx
=> :rotating_lights: prettified things

src/atoms/style/colors.ts, src/atoms/types/variants.ts, src/molecules/Select/ComboBox/ComboBox.stories.tsx, src/molecules/Select/Select.styles.ts, src/molecules/Select/Select.test.tsx, src/molecules/Select/Select.types.ts, src/molecules/Select/SingleSelect/SingleSelect.stories.tsx, src/molecules/Sieve/Sieve.styles.tsx, src/molecules/TextField/TextField.stories.tsx, src/molecules/TextField/TextField.test.tsx, src/molecules/TextField/TextField.tsx, src/organisms/FieldSelector/FieldSelector.test.tsx, src/organisms/FieldSelector/FieldSelector.tsx, src/organisms/FieldSelector/SelectorCard/SelectorCard.tsx
Userstory:
- [AB#511236](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/511236)
=> TextField variants

.run/Code coverage.run.xml, src/molecules/Chip/Chip.stories.tsx, src/molecules/Chip/Chip.styles.tsx, src/molecules/Chip/Chip.test.tsx, src/molecules/Chip/Chip.tsx, src/molecules/Chip/InteractiveChip.tsx, src/molecules/Chip/ReadOnlyChip.tsx
Also refactored how the prop types for the different chips are defined. Now you can't set both onDelete and onClick (will throw TS error)
---
Userstories:
- [AB#528554](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/528554)
- [AB#529794](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/529794)
Tasks:
- [AB#533017](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/533017)
- [AB#533018](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/533018)
- [AB#533019](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/533019)
=> New chip styling and white chip variant

src/molecules/Select/ComboBox/ComboBox.stories.tsx, src/molecules/Select/Select.styles.ts, src/molecules/Select/Select.tsx, src/molecules/Select/SelectMenuItem.tsx, src/molecules/Select/SingleSelect/SingleSelect.stories.tsx
Userstory:
- [AB#534504](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/534504)
=> :bug: Fixing width of Select Menu when item names are long

package-lock.json, package.json, src/organisms/SideBar/MenuItem.styles.ts
Fixes [AB#537686](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/537686)
=> :bug: Fix sidebar icon vertical alignment

package-lock.json, package.json, src/organisms/Template/Template.tsx
=> :bug: Fix Template.Content width being too small

.storybook/main.js, src/organisms/TopBar/Resources/ReleaseNotesDialog/FilterHeader/FilterHeader.test.tsx, src/organisms/TopBar/Resources/ReleaseNotesDialog/FilterHeader/FilterHeader.tsx
- [AB#538867](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/538867)
=> :bug: Fix bad ReleaseNotes url in topbar resources

src/atoms/hooks/useSelect.ts, src/molecules/Select/AddTagItem.tsx, src/molecules/Select/ComboBox/ComboBox.test.tsx, src/molecules/Select/ListSelectMenu.tsx, src/molecules/Select/Select.tsx, src/molecules/Select/Select.types.ts
Closes #734
- [AB#538961](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/538961)
=> :bug: Fix onAddItem being called twice when hitting 'Enter' on add tag menu item

src/molecules/Dialog/Dialog.stories.tsx, src/molecules/Dialog/Dialog.test.tsx, src/molecules/Dialog/DialogAction.tsx
[AB#541789](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/541789)
=> :bug: Fixed DialogAction actually using the disabled prop on the button

package-lock.json, package.json, src/organisms/Template/Template.tsx
Userstory:
- [AB#548845](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/548845)
---
Bumping version was intentional since I want people to be able to try it out as fast as possible
=> Adding border-box style rule

src/atoms/style/colors.ts, src/molecules/Select/ComboBox/ComboBox.stories.tsx, src/molecules/Select/ComboBox/ComboBox.tsx, src/molecules/Select/Select.styles.ts, src/molecules/Select/Select.test.tsx, src/molecules/Select/Select.tsx, src/molecules/Select/Select.types.ts, src/molecules/Select/SingleSelect/SingleSelect.stories.tsx, src/molecules/Select/SingleSelect/SingleSelect.tsx, src/molecules/TextField/TextField.tsx
Userstory:
- [AB#540031](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/540031)
=> Aligning Select component helper styling with TextField

src/organisms/TopBar/Account/Account.test.tsx, src/organisms/TopBar/Account/ImpersonateButton.tsx, src/organisms/TopBar/Account/ImpersonateMenu/Actions.tsx, src/organisms/TopBar/Account/ImpersonateMenu/CreateNewUser/CreateNewUser.test.tsx, src/organisms/TopBar/Account/ImpersonateMenu/hooks/useCreateImpersonation.ts
Userstory:
- [AB#545012](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/545012)
=> :adhesive_bandage: Avoid reload when starting a user impersonation

src/organisms/SideBar/MenuItem.tsx, src/organisms/SideBar/MenuItem.utils.test.ts, src/organisms/SideBar/MenuItem.utils.ts
Solves [AB#546933](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/546933)
=> :recycle: Simplified isCurrentUrl

src/molecules/Dialog/Dialog.tsx
Also changing to forwardRef component
=> Fixing Dialog overriding styles

.storybook/main.js, src/atoms/utils/auth_environment.ts, src/organisms/TopBar/Account/Account.test.tsx, src/organisms/TopBar/Account/Account.tsx, src/organisms/TopBar/Account/AccountButton.tsx, src/organisms/TopBar/Account/ImpersonateButton.tsx, src/organisms/TopBar/Account/ImpersonateMenu/Actions.tsx, src/organisms/TopBar/Account/ImpersonateMenu/Impersonate.constants.ts, src/organisms/TopBar/Account/ImpersonateMenu/hooks/useCreateImpersonation.ts, src/organisms/TopBar/Account/ImpersonateMenu/hooks/useEditImpersonation.ts, src/organisms/TopBar/Account/ImpersonateMenu/hooks/useStartImpersonation.ts, src/organisms/TopBar/Account/ImpersonateMenu/hooks/useStopImpersonation.ts
Userstory:
- [AB#551125](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/551125)
=> :adhesive_bandage: Fix impersonation button being visible in production

src/organisms/SideBar/CreateItem.styles.ts, src/organisms/SideBar/CreateItem.test.tsx, src/organisms/SideBar/CreateItem.tsx, src/organisms/SideBar/SideBar.tsx
[AB#553234](https://dev.azure.com/Equinor/Johan%20Sverdrup%20Digitalisation/_workitems/edit/553234)
=> 💄 Active prop in sidebar - create button

src/molecules/RichTextEditor/RichTextEditor.styles.ts, src/molecules/RichTextEditor/RichTextEditor.test.tsx, src/molecules/RichTextEditor/RichTextEditor.tsx
[AB#553709](https://dev.azure.com/Equinor/Johan%20Sverdrup%20Digitalisation/_workitems/edit/553709)
=> 💄 Add highlighting to rich text editor

src/molecules/ProfileAvatar/ProfileAvatar.test.tsx, src/molecules/ProfileAvatar/ProfileAvatar.tsx, src/organisms/TopBar/Account/ImpersonateMenu/CreateOrEditUser/CreateOrEditUser.test.tsx, src/organisms/TopBar/Account/ImpersonateMenu/CreateOrEditUser/CreateOrEditUser.tsx, src/organisms/TopBar/Account/ImpersonateMenu/DeleteUser/DeleteUser.styles.ts, src/organisms/TopBar/Account/ImpersonateMenu/DeleteUser/DeleteUser.tsx, src/organisms/TopBar/Account/ImpersonateMenu/ImpersonateMenu.tsx, src/organisms/TopBar/Account/ImpersonateMenu/UserImpersonation.styles.ts, src/organisms/TopBar/Account/ImpersonateMenu/UserImpersonation.tsx, src/organisms/TopBar/Account/ImpersonateMenu/hooks/useCreateImpersonation.ts, src/tests/mockHandlers.ts
Userstory:
- [AB#550539](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/550539)
=> Design tweaks on user impersonation

src/molecules/FileProgress/FileProgress.stories.tsx, src/molecules/FileProgress/FileProgress.tsx
[AB#554450](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/554450)
=> :bulb: Add docs to FileProgress progressPercent

src/atoms/style/colors.stories.tsx, src/molecules/Dialog/Dialog.stories.tsx, src/molecules/Dialog/Dialog.test.tsx, src/molecules/Dialog/Dialog.tsx, src/molecules/Dialog/DialogAction.tsx, src/organisms/TopBar/Account/Account.test.tsx, src/organisms/TopBar/Account/ImpersonateMenu/ImpersonateMenu.styles.ts, src/organisms/TopBar/Account/ImpersonateMenu/ImpersonateMenu.tsx, src/providers/providers.stories.tsx
Userstories:
- [AB#555039](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/555039)
- [AB#555040](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/555040)
- [AB#555042](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/555042)
---
Fixing search in user impersonation not working
Added isLoading prop to DialogActions
Adding story for how theming works
=> Fix search in impersonation+++

src/molecules/RichTextDisplay/RichTextDisplay.tsx
[AB#556163](https://dev.azure.com/Equinor/Johan%20Sverdrup%20Digitalisation/_workitems/edit/556163)
=> 🎨 Expand API of RichTextDisplay

src/atoms/style/colors.stories.tsx, src/atoms/style/colors.ts, src/atoms/style/darkTokens.ts, src/atoms/style/lightTokens.ts
[AB#556280](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/556280)
=> :lipstick: Added two custom ACL colors to colors token

src/organisms/SideBar/MenuItem.styles.ts, src/organisms/SideBar/MenuItem.test.tsx, src/organisms/SideBar/MenuItem.tsx
- [AB#557089](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/557089)
=> :lipstick: Remove :focus styling in SideBar/MenuItem

src/organisms/TopBar/Account/Account.styles.ts, src/organisms/TopBar/ApplicationDrawer/ApplicationDrawer.tsx, src/organisms/TopBar/FieldMenu/FieldMenu.tsx, src/organisms/TopBar/Guidelines/Guidelines.tsx, src/organisms/TopBar/Notifications/NotificationsInner.tsx, src/organisms/TopBar/Resources/Resources.tsx, src/organisms/TopBar/Settings.tsx, src/organisms/TopBar/TopBar.styles.ts, src/organisms/TopBar/TopBar.test.tsx, src/organisms/TopBar/TopBar.tsx
- [AB#556167](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/556167)
=> :children_crossing: Make clicking header go to '/' (path can be overridden) using Link

src/molecules/FileProgress/CompactFileProgress.tsx, src/molecules/FileProgress/FileProgress.stories.tsx, src/molecules/FileProgress/FileProgress.test.tsx, src/molecules/FileProgress/FileProgress.tsx, src/molecules/FileProgress/RegularFileProgress.tsx
- [AB#554451](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/554451)
=> FileProgress onDelete returning promise

src/atoms/hooks/useSelect.ts, src/molecules/Select/ComboBox/ComboBox.stories.tsx, src/molecules/Select/ComboBox/ComboBox.test.tsx
- [AB#557945](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/557945)
Solves #799
=> :bug: Fix form onSubmit being called when hitting {Enter} inside of Select components

src/organisms/Template/Template.tsx
Fixes: [AB#558470](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/558470)
=> :lipstick: Add default background to dialog elements

src/organisms/TopBar/Account/ImpersonateMenu/DeleteUser/DeleteUser.styles.ts
[AB#558548](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/558548)
=> :bug: Add missing padding to TopBar.Account/Impersonation/DeleteUser

src/atoms/style/darkTokens.ts
- [AB#561977](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/561977)
=> :bug: Override missing text colors in dark tokens

config/config_files/workflows/e2e.yaml
- [AB#563187](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/563187)
=> :construction_worker: Make E2E workflow run when PR is ready for review

src/organisms/TopBar/Account/ImpersonateMenu/ImpersonateMenu.tsx
- [AB#563384](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/563384)
=> :bug: Fix impersonate menu not being static width on overview

src/molecules/ListItem/ListItem.tsx, src/organisms/TopBar/Account/Account.test.tsx, src/organisms/TopBar/Account/ImpersonateMenu/ImpersonateMenu.test.tsx
- [AB#562948](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/562948)
=> :bug: Fix height of ListItem (with border as well)

src/molecules/Stepper/Step/Step.tsx
- [AB#555051](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/555051)
=> :bug: Fix toggling onlyShowCurrentStepLabel breaking

src/molecules/Search/Search.tsx, src/molecules/Select/Select.styles.ts, src/molecules/TextField/TextField.tsx
- [AB#562949](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/562949)
- [AB#562950](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/562950)
- [AB#562951](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/562951)
- [AB#563186](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/563186)
=> :lipstick: Add background light medium bg on hover

src/atoms/hooks/useSelect.ts, src/molecules/Select/ComboBox/ComboBox.stories.tsx, src/molecules/Select/ComboBox/ComboBox.test.tsx, src/molecules/Select/Select.styles.ts, src/molecules/Select/Select.tsx, src/molecules/Select/Select.types.ts, src/molecules/index.ts
- [AB#567502](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/567502)
=> ComboBox - Custom value component

src/molecules/FullPageSpinner/FullPageSpinner.test.tsx, src/molecules/FullPageSpinner/FullPageSpinner.tsx, src/providers/LoadingProvider.test.tsx, src/providers/LoadingProvider.tsx
- [AB#564916](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/564916)
=> :children_crossing: Make LoadingProvider show elements under it

src/organisms/SideBar/CreateItem.styles.ts, src/organisms/SideBar/CreateItem.tsx
[AB#572261](https://dev.azure.com/Equinor/Johan%20Sverdrup%20Digitalisation/_workitems/edit/572261)
=> 💄 Create button in sidebar - ui adjustments

src/molecules/DatePicker/DatePicker.stories.tsx, src/molecules/DatePicker/DatePicker.test.tsx, src/molecules/DatePicker/DatePicker.tsx, src/molecules/index.ts
- [AB#572669](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/572669)
=> :sparkles: Add default format and locale to DatePicker

src/molecules/RichTextEditor/index.ts, src/organisms/Filter/ButtonWithMenu.tsx, src/organisms/Filter/Filter.stories.tsx, src/organisms/Filter/Filter.styles.ts, src/organisms/Filter/Filter.test.tsx, src/organisms/Filter/Filter.tsx, src/organisms/Filter/Filter.types.ts, src/organisms/Filter/QuickFilter.tsx, src/organisms/Filter/Sorting.tsx, src/organisms/index.ts
- [AB#577259](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/577259)
=> :sparkles: Added sort and quick filter to Filter component

src/organisms/Status/collections/MissingAccessToApp.test.tsx, src/organisms/Status/collections/MissingAccessToApp.tsx
[AB#573893](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/573893)
=> :bug: Fix bad url in MissingAccessToApp component

src/molecules/FileProgress/CompactFileProgress.styles.tsx, src/molecules/FileProgress/CompactFileProgress.tsx, src/molecules/FileProgress/FileProgress.utils.tsx
Userstory:
- [AB#572768](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/572768)
- [AB#556011](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/556011)
=> :lipstick: Change border styling for CompactFileProgress

src/molecules/RichTextEditor/RichTextEditor.styles.ts
Userstory:
- [AB#575700](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/575700)
=> :lipstick: Change <th> bg color when lightBackground is false in RTE

src/organisms/Filter/Filter.styles.ts
Userstory:
- [AB#582131](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/582131)
=> :bug: Fix Filter component height breaking if value chips are on more than 1 row

src/organisms/TopBar/Settings.stories.tsx, src/organisms/TopBar/Settings.test.tsx, src/organisms/TopBar/Settings.tsx
- [AB#586211](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/586211)
=> :sparkles: Add "children" prop to TopBar.Settings

src/organisms/FieldSelector/FieldSelector.tsx, src/organisms/Template/Template.tsx
- [AB#584958](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/584958)
=> :lipstick: Make 1280px the default max width of elements inside Template.Content

src/molecules/Stepper/Stepper.jsdom.test.tsx, src/molecules/Stepper/Stepper.stories.tsx, src/molecules/Stepper/Stepper.test.tsx, src/providers/StepperProvider.jsdom.test.tsx, src/providers/StepperProvider.tsx
[AB#597017](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/597017)
=> :sparkles: StepperProvider - sync to url param

src/organisms/PageTitle/PageTitle.test.tsx, src/organisms/PageTitle/PageTitle.tsx, src/organisms/index.ts
Userstory: [AB#597076](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/597076)
Task: [AB#601644](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/601644)
=> :sparkles: Created PageTitle component

src/atoms/utils/date.test.ts, src/atoms/utils/date.ts, src/molecules/DatePicker/DatePicker.test.tsx, src/molecules/DatePicker/DatePicker.tsx
Userstory: [AB#596894](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/596894)
Tasks:
- [AB#599075](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/599075)
- [AB#599080](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/599080)
=> :lipstick: Change default date formats

src/molecules/FileProgress/CompactFileProgress.tsx, src/molecules/FileProgress/FileProgress.stories.tsx, src/molecules/FileProgress/FileProgress.test.tsx, src/molecules/FileProgress/FileProgress.tsx, src/molecules/FileProgress/FileProgress.types.ts, src/molecules/FileProgress/RegularFileProgress.tsx, src/molecules/index.ts
- [AB#601899](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/601899)
- [AB#601898](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/601898)
=> :label: Update types for FileProgress component

src/atoms/style/colors.ts, src/molecules/RichTextEditor/RichTextEditor.jsdom.test.tsx, src/molecules/RichTextEditor/RichTextEditor.styles.ts, src/molecules/RichTextEditor/RichTextEditor.test.tsx, src/molecules/RichTextEditor/RichTextEditor.tsx, src/molecules/Select/Select.jsdom.test.tsx, src/molecules/Select/Select.styles.ts, src/molecules/Select/Select.tsx
- [AB#603677](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/603677)
=> :lipstick: Align field variants for Select/RichTextEditor components

src/atoms/hooks/index.ts, src/atoms/hooks/usePrefetchRichTextImages.test.tsx, src/atoms/hooks/usePrefetchRichTextImages.ts, src/atoms/utils/forms.test.tsx, src/atoms/utils/forms.ts, src/atoms/utils/index.ts, src/atoms/utils/richtext.test.ts, src/atoms/utils/richtext.ts, src/molecules/RichTextEditor/RichTextEditor.test.tsx, src/molecules/RichTextEditor/RichTextEditor.tsx, src/molecules/Select/Select.jsdom.test.tsx, src/molecules/Select/Select.tsx
- [AB#604893](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/604893)
=> :sparkles: Create hook to prefetch rich text images based on rich text values

src/molecules/Select/AddTagItem.tsx, src/molecules/Select/ComboBox/ComboBox.test.tsx, src/molecules/Select/ComboBox/ComboBox.tsx, src/molecules/Select/ListSelectMenu.tsx, src/molecules/Select/Select.test.tsx, src/molecules/Select/Select.types.ts, src/molecules/Select/SingleSelect/SingleSelect.test.tsx, src/molecules/Select/SingleSelect/SingleSelect.tsx
[AB#605682](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/605682)
=> :sparkles: Add 'itemSingularWord' prop so you can change from "Add tag" -> "Add category" for example

.github/workflows/build_deploy_radix.yaml, .github/workflows/promote.yaml, .github/workflows/push.yaml, radixconfig.yaml
[AB#596883](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/596883)
=> :construction_worker: Setup deploy / promote flow, now automatically promotes to production when publishing

src/molecules/FullPageSpinner/FullPageSpinner.tsx
[AB#599234](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/599234)
=> Fix full page spinner centering

src/atoms/utils/date.stories.tsx, src/atoms/utils/date.ts, src/molecules/FileProgress/CompactFileProgress.tsx, src/molecules/FileProgress/FileProgress.stories.tsx, src/molecules/FileProgress/FileProgress.test.tsx, src/molecules/FileProgress/FileProgress.tsx, src/molecules/FileProgress/FileProgress.types.ts, src/molecules/FileProgress/RegularFileProgress.styles.tsx, src/molecules/FileProgress/RegularFileProgress.tsx, src/molecules/Select/Select.styles.ts, src/molecules/Select/Select.test.tsx
[AB#601092](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/601092)
=> :bug: Fix placeholder text in Select, :sparkles: Make "onDelete" in FileProgress optional

src/organisms/Filter/Filter.stories.tsx, src/organisms/Filter/Filter.styles.ts, src/organisms/Filter/Filter.tsx
Userstory:
[AB#604604](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/604604)
Tasks:
- [AB#610671](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/610671)
- [AB#610672](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/610672)
- [AB#610673](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/610673)
- [AB#610676](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/610676)
=> Filter component design feedback

src/atoms/style/spacings.ts, src/molecules/Button/Button.docs.mdx, src/molecules/Button/Button.stories.tsx, src/molecules/Button/Button.test.tsx, src/molecules/Button/Button.tsx, src/molecules/Button/Button.utils.test.ts, src/molecules/Button/Button.utils.ts, src/molecules/Dialog/Dialog.stories.tsx, src/molecules/Dialog/DialogAction.tsx, src/molecules/index.ts
[AB#609084](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/609084)
=> Add 'loading' prop to button

package.json, src/atoms/style/colors.ts, src/atoms/style/lightTokens.ts, src/atoms/utils/reactquery.ts
[AB#612031](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/612031)
=> Adding dataviz primary / new default query options

package.json, src/organisms/Template/Template.tsx
[AB#615833](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/615833)
=> :sparkles: Added Template.WithoutScrollGutter className

config/config_files/eslint.config.mjs, config/config_files/test-utils/browsertest-utils.tsx, config/config_files/test-utils/setupBrowserTests.ts, src/tests/setupBrowserTests.ts
Adjusting config according to:
https://mswjs.io/docs/recipes/vitest-browser-mode/
https://vitest.dev/guide/test-context.html#typescript
=> 🐛 Stabilize mocking in vitest browser tests

src/organisms/ToggleGroup/ToggleGroup.stories.tsx, src/organisms/ToggleGroup/ToggleGroup.test.tsx, src/organisms/ToggleGroup/ToggleGroup.tsx, src/organisms/ToggleGroup/ToggleGroup.types.ts, src/organisms/ToggleGroup/ToggleGroupOption.tsx, src/organisms/ToggleGroup/index.ts, src/organisms/index.ts
[AB#609003](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/609003)
=> :sparkles: ToggleGroup

src/organisms/Filter/Filter.tsx
[AB#618362](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/618362)
=> :adhesive_bandage: Move ID that is passed into Filter component to the wrapper

.github/workflows/tests.yaml, src/organisms/ToggleGroup/ToggleGroup.stories.tsx, src/organisms/ToggleGroup/ToggleGroup.test.tsx, src/organisms/ToggleGroup/ToggleGroup.tsx, src/organisms/ToggleGroup/ToggleGroup.types.ts, src/organisms/ToggleGroup/ToggleGroupOption.tsx
Userstory: [AB#609003](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/609003)
Tasks:
- [AB#621407](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/621407)
- [AB#621423](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/621423)
=> :lipstick: Adjust ToggleGroup height

src/molecules/Select/ComboBox/ComboBox.stories.tsx, src/molecules/Select/ComboBox/ComboBox.test.tsx, src/molecules/Select/Select.tsx, src/molecules/Select/Select.types.ts
[AB#618222](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/618222)
=> :sparkles: Add possibility to pass fn to showAsSelectedText prop (ComboBox)

src/atoms/hooks/useSelect.ts, src/molecules/Select/Select.tsx
[AB#625810](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/625810)
=> :bug: Fix focus bug in Select components

src/molecules/Select/ComboBox/ComboBox.stories.tsx, src/molecules/Select/ComboBox/ComboBox.test.tsx, src/molecules/Select/ComboBox/ComboBox.tsx, src/molecules/Select/GroupedSelectMenu.tsx, src/molecules/Select/ListSelectMenu.tsx, src/molecules/Select/Select.tsx, src/molecules/Select/Select.types.ts, src/molecules/Select/SelectMenuItem.tsx, src/molecules/Select/SelectMenuItem.utils.ts, src/molecules/Select/SingleSelect/SingleSelect.stories.tsx, src/molecules/Select/SingleSelect/SingleSelect.test.tsx, src/molecules/Select/SingleSelect/SingleSelect.tsx
[AB#627295](https://dev.azure.com/Equinor/DPP%20Upscaling%20of%20digital%20solutions/_workitems/edit/627295)
=> ✨ Customizable select menu item

src/molecules/Tabs/Tab.styles.ts, src/molecules/Tabs/Tab.tsx, src/molecules/Tabs/Tabs.stories.tsx, src/molecules/Tabs/Tabs.test.tsx, src/molecules/Tabs/Tabs.types.ts
Userstory: [AB#624745](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/624745)
Task: [AB#631234](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/631234)
=> :sparkles: Added count to Tabs

.github/workflows/build_deploy_radix.yaml
- This PR fixes the build and deploy of storybook to radix
=> :construction_worker: Change rx command to build and deploy

.github/workflows/build_deploy_radix.yaml
- AB#USER_STORY_ID
- AB#TASK_ID
---
- This PR fixes/adds ...
1. Navigate to `<url>`
2. ...
=> :alembic: --to-environment

.github/workflows/pull_request.yaml, src/molecules/SelectionControls/Checkbox/Checkbox.stories.tsx
- AB#USER_STORY_ID
- AB#TASK_ID
---
- This PR fixes/adds ...
1. Navigate to `<url>`
2. ...
=> :alembic: Test feature deploy

src/providers/TutorialHighlightingProvider/TutorialPopover/TutorialPopover.tsx
Changed to the one used on the figma design.
- [] Needs to be tested locally by reviewer
=> 💄 Adjusted the shade used on tutorial cards

src/organisms/Filter/AutoCompleteMenu.tsx, src/organisms/Filter/AutoCompleteText.tsx, src/organisms/Filter/Filter.stories.tsx, src/organisms/Filter/Filter.styles.ts, src/organisms/Filter/Filter.test.tsx, src/organisms/Filter/Filter.tsx, src/organisms/Filter/Filter.types.ts, src/organisms/Filter/Filter.utils.ts
- [AB#610010](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/610010)
- [AB#650831](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/650831)
---
- This PR adds 'autoCompleteOptions' and 'onAutoComplete' to Filter component
=> :sparkles: Added auto complete functionality to Filter component
