equinor/amplify-component-lib

- package.json
- src/providers/AuthProvider/AuthProviderInner.tsx
- src/utils/auth_environment.ts
Acquire token error handling has now been moved up one level to the `AuthProviderInner` component. Also added more logging so we have more knowledge when a acquire token error happens.
> Moved acquire token error handling

- package.json
- src/providers/AuthProvider/AuthProviderInner.tsx
Got an endless refresh loop when using the new automatic refresh release when running Tools locally, this commit should fix that
> Fix endless refresh loop

- package.json
- src/hooks/useNotifications.ts
Fixes a bug I had in Depthconversion where there was a NotificationDTO from the backend where SequenceNumber and Read can be both null and undefined
> Fix types for useNotifications

- package.json
- src/providers/AuthProvider/AuthProviderInner.tsx
Changed to only clearing msal related localstorage when having to clear localstorage because of expired tokens inside the AuthProvider component
> Only clearing msal related localstorage

- src/utils/date.test.ts
- src/utils/date.ts
Changed date display for dates within last week relative to today, so that Tuesday at 12:00 means coming Tuesday and not last Tuesday. Last Tuesday is displayed 15. August at 12:00.
> ✅ Improved date util

- package.json
- src/hooks/useSignalRMessages.ts
Removing the 'host' parameter since we always want to use the portal-url based on which environment we are in
> Removing 'host' parameter from useSignarlR-hook

- Dockerfile
- config/config_files/Dockerfile
- config/config_files/client.yaml
- config/config_files/env.sh
- config/config_files/nginx.conf
- config/config_files/securityheaders.conf
- config/install.sh
- proxy/nginx.conf
- proxy/securityheaders.conf
Fixed a bug where we weren't using the nginx conf file
> ✨  add security headers

- src/utils/date.test.ts
- src/utils/date.ts
When using <Input type='date' > date string format YYYY-MM-DD requires 2-digit day and month.
> 🐛 Ensure 2-digit day and month

- .github/workflows/pr_actions.yaml
- config/config_files/client.yaml
- package.json
- src/components/DataDisplay/DataCard.tsx
- src/components/DataDisplay/InfoElement.stories.tsx
- src/components/DataDisplay/Workflow/WorkflowStatusBar.tsx
- src/components/Feedback/Progress/FileProgress.tsx
- src/components/Inputs/CopyText.tsx
- src/components/Inputs/PageMenu.tsx
- src/components/Navigation/SideBar/MenuItem.tsx
- src/components/Navigation/SideBar/ToggleOpen.tsx
- Fixing styled-component props where $ is missing
- Fixing width of CopyText's wrapper not following width of element
- Bumping github action node versions to 20.x
> Fixing missing $ on some styled-component's props, also fixing width of CopyText wrapper

- README.md
- config/config_files/workflows/build_deploy_radix.yaml
- config/config_files/workflows/notify.yaml
- config/config_files/workflows/promote.yaml
- config/config_files/workflows/push.yaml
- config/github_actions_deployment_list.txt
- config/install-deployment-files.sh
> :sparkles: :construction_worker: ability to deploy to radix from github

- src/components/Navigation/SideBar/SideBar.test.tsx
- src/components/Navigation/SideBar/SideBar.tsx
- [AB#472375](https://dev.azure.com/Equinor/4319082b-29ba-4111-a20b-c04f55c7e7c6/_workitems/edit/472375)
- [AB#472376](https://dev.azure.com/Equinor/4319082b-29ba-4111-a20b-c04f55c7e7c6/_workitems/edit/472376)
- [AB#472377](https://dev.azure.com/Equinor/4319082b-29ba-4111-a20b-c04f55c7e7c6/_workitems/edit/472377)
> Add 'showCreate' prop to sidebar

- package.json
- src/components/Navigation/TopBar/ApplicationDrawer/ApplicationDrawer.tsx
Change application drawer button to ghost to match the rest of topbar
> 💄 Change to ghost button for application drawer

- config/config_files/.eslintrc.js
- src/components/Inputs/ComboBox/ComboBox.styles.ts
- src/components/Inputs/ComboBox/ComboBox.test.tsx
- src/components/Inputs/ComboBox/ComboBox.tsx
- src/components/Inputs/ComboBox/ComboBoxMenuItem.tsx
[AB#448602](https://dev.azure.com/Equinor/DPP%20Upscaling%20of%20digital%20solutions/_workitems/edit/448602)
Also extended linting configuration to be able to name not used variables. Various use cases.
Currently in need to use with typescripts `infer`
```
type ContainsDot<TParam extends string> =
TParam extends `${infer _Start}.${infer _End}` ? TParam : never;
```
> Make combox stylable

- src/components/Navigation/TopBar/Settings.tsx
The `onChange` function should be able to be assigned other types other than string
> Fix onChange type in ISettingsSections interface

- package-lock.json
- package.json
- src/components/Inputs/ComboBox/ComboBox.tsx
- src/components/Inputs/ComboBox/ComboBox.types.ts
- src/components/Inputs/ComboBox/ComboBox.utils.ts
- src/components/Inputs/ComboBox/ComboBoxMenu.tsx
- src/components/Inputs/ComboBox/ComboBoxMenuItem.tsx
- src/components/Inputs/ComboBox/GroupedComboBoxMenu.tsx
- src/components/index.ts
- Exporting new type `ComboBoxOptionRequired` which includes the required types for an item in the combo box
---
Creds to @arkadiy93 for showing me [structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone)
> Clean up types in ComboBox so it is easier to use

- package-lock.json
- package.json
- src/components/Navigation/SideBar/MenuItem.tsx
[AB#481437](https://dev.azure.com/Equinor/DPP%20Upscaling%20of%20digital%20solutions/_workitems/edit/481437)
As navigation is handled by Link component, onClick is not a required param.
```
<Link to={link} ... />
```
> 🩹 Make onClick optional in MenuItem

- package-lock.json
- package.json
- src/providers/AuthProvider/AuthProviderInner.tsx
Needs to be tested before moving to prod (idea is to test in LQT after this has been published)
---
Tested locally with build-and-use against dasha and pwex now and seems to be working
> Avoid showing 'unauthorized' before refreshing to login

- config/config_files/playwright.config.ts
Halved the timeout, IMHO, does not really make sense unless something is wrong with the test in which case it should be fixed instead
> :hammer: reduced playwright expect timeout time

- config/config_files/CODEOWNERS
If your application has a server directory, we wan't the amplify-backend team to be assigned to pullrequest made in there.
> ✨ Add amplify-backend as codeowners for server directory

- package-lock.json
- package.json
- src/components/Inputs/ComboBox/ComboBox.stories.tsx
- src/components/Inputs/ComboBox/ComboBox.styles.ts
- src/components/Inputs/ComboBox/ComboBox.test.tsx
- src/components/Inputs/ComboBox/ComboBox.tsx
- src/components/Inputs/ComboBox/ComboBox.types.ts
- src/components/Inputs/ComboBox/ComboBox.utils.test.ts
- src/components/Inputs/ComboBox/ComboBox.utils.ts
- src/components/Inputs/ComboBox/ComboBoxMenuItem.tsx
Changes related to: 
[AB#484853](https://dev.azure.com/Equinor/DPP%20Upscaling%20of%20digital%20solutions/_workitems/edit/484853)
> 🎨 Combobox adjustments

- package.json
- src/components/Inputs/ComboBox/ComboBox.test.tsx
- src/components/Inputs/ComboBox/ComboBoxMenuItem.tsx
- src/hooks/useComboBox.ts
[AB#508177](https://dev.azure.com/Equinor/Johan%20Sverdrup%20Digitalisation/_workitems/edit/508177)
> 🎨 Combobox - avoid checking children on parent select

- src/components/DataDisplay/Chip/InteractiveChip.tsx
This pull request fixes a breaking change in combox/chip component.
The current `InteractiveChip` is selecting the `close` icon by using the `name` prop.
This works in storybook and local dev mode since all of the icons gets loaded in `icon.stories.tsx` story using `Icon.add()`.
When building for production the loading of the icons get treeshaken out since the code is not imported by the user. Causing the `Chip` component to crash since there does not exist an icon named `close`.
Swaps the `InteractiveChip` from using the `name` to passing the `close`  icon to the `data` prop.
> fix: changes from using name prop to data prop so that users dont need to load icon manually

- src/components/Inputs/RichTextEditor/RichTextEditor.styles.ts
This pull request fixes an issue with the `RichTextEdtior` in dark mode. The text color for `p` tags and the background color was using hardcoded color. Fixed the issue by swapping the hardcoded colors for eds tokens.
before: 
after:
> fix: changes the text color for p tags and the background color to use

- src/components/Feedback/ConfirmationPopup.tsx
This pull request fixes an issue with `ConfirmationPopup` where to close button shrinks when the header text becomes to long by setting a `min-width` on the button. It is possible to set the width, but the header is often dynamic, referencing the name/title of a resource which can have a unknown length.
before:
after:
> fix: stop close button from shrinking ConfirmationPopup when the header text is long

- src/components/Inputs/RichTextEditor/MenuBar/MenuButton.tsx
This pull request fixes an issue where clicking the `MenuButton` submits forms if the `RichTextEditor` is used in a form.
Fixes the issue by adding `type="button"` to the `MenuButton`
> fix: add type button to MenuButton

- src/components/Inputs/RichTextEditor/RichTextEditor.styles.ts
This pull request changes the color of the placeholder text for the `RichTextEditor` to match the placeholder color of other eds/amplify input fields.
before: 
after:
> fix: changes the placeholder color for RichTextEditor to match other input field color

- src/organisms/TopBar/TopBar.styles.ts
Fixes an error in parsing the value for the 'border' property. Previously, the code was setting the border to '1px solid none' instead of '1px solid transparent' when the element was not selected.
Error:
```
Error in parsing value for ‘border’.  Declaration dropped. 5339:6:13108
Elements matching selector: .kFmpSZ
NodeList [ button.Button__ButtonBase-sc-1hs0myn-1.ihpSAG.sc-SrAaV.kFmpSZ ]
​
0: <button class="Button__ButtonBase-sc-1h… ihpSAG sc-SrAaV kFmpSZ" type="button" tabindex="0" data-testid="field-selector-top-bar-button">
​
length: 1
​
<prototype>: NodeListPrototype { item: item(), keys: keys(), values: values(), … }
```
> Fix error in parsing value for 'border' 

- src/organisms/TopBar/TopBar.tsx
Just adding back withHover prop to appIcon in topbar, so it works "as before"
> :adhesive_bandage: Add withHover prop to app icon in topbar

- .github/workflows/secret_scanning.yaml
- config/config_files/workflows/secret_scanning.yaml
Previously the `secret_scanning.yaml` uses the arguments `debug` and `no-verification` which was more like a testing.
Setting up `--only-verified` which should be more stable as will look for only output verified results.
> fix: update secret scanning workflow to use only verified

- src/organisms/TopBar/Resources/ReleaseNotesDialog/ReleasePosts/ReleasePost/ReleasePost.tsx
- src/tests/mockHandlers.ts
Bug:
- [AB#540813](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/540813)
> :bug: Fix 'Read more' in long release notes

- src/atoms/hooks/useAmplifyKit.ts
- src/molecules/RichTextDisplay/RichTextDisplay.stories.tsx
- src/molecules/RichTextDisplay/RichTextDisplay.tsx
- src/molecules/RichTextEditor/EditorProvider.tsx
- src/molecules/RichTextEditor/index.ts
1. Lets me return the editor instance out of the display rich text component
2. Lets me pass extensions as prop to the display rich text component
3. Makes the content prop reactive so that it works better when fetching data
4. Lets you exclude more extensions from the extension registration
5. Adds the storybook for display rich text compound component
> Turns display rich text into a compound component

- src/molecules/InfoElement/InfoElement.test.tsx
- src/molecules/InfoElement/InfoElement.tsx
- [AB#531491](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/531491)
> :children_crossing: Make InfoElement props less strict to allow setting copyable/capitalize dynamically

- src/atoms/enums/SpacingsMode.ts
- src/atoms/enums/index.ts
- src/atoms/style/spacings.stories.tsx
- [AB#557979](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/557979)
> Spacings mode

- src/atoms/hooks/useSelect.ts
- src/molecules/Select/ComboBox/ComboBox.test.tsx
- src/molecules/Select/Select.types.ts
Solves #800
- [AB#557944](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/557944)
> :bug: Fix search in combobox loosing focus when searching with preselected items

- package-lock.json
- package.json
- src/molecules/Dialog/Dialog.stories.tsx
- src/molecules/Dialog/Dialog.styles.ts
- src/molecules/Dialog/Dialog.test.tsx
- src/molecules/Dialog/Dialog.tsx
- [AB#558763](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/558763)
> :sparkles: Added contentMaxHeight prop to Dialog

- src/molecules/Select/Select.test.tsx
- src/molecules/Select/SelectMenuItem.tsx
> :bug: Fix Select components calling onSubmit when users select items (with keyboard or mouse)

- src/organisms/Filter/Filter.stories.tsx
- src/organisms/Filter/Filter.styles.ts
- src/organisms/Filter/Filter.test.tsx
- src/organisms/Filter/Filter.tsx
- [AB#561296](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/561296)
- [AB#561298](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/561298)
> Controlled filter search

- src/organisms/TopBar/Notifications/Notifications.stories.tsx
- src/organisms/TopBar/Notifications/Notifications.test.tsx
- src/organisms/TopBar/Notifications/NotificationsInner.tsx
I need to be able to close the notifications dropdown programatically in PWEX. This gives us the option to access the onClose handler inside the notifications component
> :sparkles: Lets child components trigger the onClose handler in the notifications topbar

- config/config_files/nginx.conf
This PR addresses the issue of exposing the env.sh file across all applications. The current setup makes this script accessible, but nginx is properly configured to prevent code execution or any exploit agains the file.
> [!NOTE]
> Although  The file/content do not appear to be immediately exploitable, exposing this file might not be a best practice as it reveal some server configuration.
**_A more secure/better solution would be to remove the file from the publicly accessible directory entirely._**
Maybe we should move the env.sh outside the webserver’s public directory and modify the docker image to run the script on start container from a different directory.
> fix: deny access to env.sh

- .storybook/addons/SpacingsAddon/withSpacingsMode.ts
- src/atoms/hooks/useSelect.ts
- src/molecules/InfoElement/CopyText.test.tsx
- src/molecules/Select/GroupedSelectMenu.tsx
- src/molecules/Select/ListSelectMenu.tsx
- src/molecules/Select/Select.styles.ts
- src/molecules/Select/Select.types.ts
- src/molecules/Select/SelectMenuItem.tsx
- src/molecules/Select/SingleSelect/SingleSelect.jsdom.test.tsx
- src/molecules/Select/SingleSelect/SingleSelect.test.tsx
Userstory:
- [AB#572802](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/572802)
> :lipstick: Add selected color for SingleSelect menu items

- src/organisms/Status/collections/ApiResponseError.stories.tsx
- src/organisms/Status/collections/ApiResponseError.test.tsx
- src/organisms/Status/collections/ApiResponseError.tsx
- src/organisms/Status/collections/index.ts
User story: [AB#591012](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/591012)
> :sparkles: wrap status components into ApiResponseError

- Dockerfile
- config/config_files/Dockerfile
- config/config_files/env.sh
- secrets.sh
Premo, dasha, js embark (probably all) all failed to build docker image, and couldnt deploy to radix. 
This version bump seems to fix it.
> :wrench: Fix for acl and common dockerfile

- src/organisms/SideBar/CreateItem.styles.ts
- src/organisms/SideBar/MenuItem.styles.ts
- src/organisms/SideBar/SideBar.styles.ts
[AB#585148](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/585148)
> :children_crossing: Make SideBar menu items top container scrollable

- src/atoms/style/darkTokens.ts
- src/atoms/style/lightTokens.ts
- [AB#635132](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/635132)
---
- This PR adds missing text colors css variables for the typography table cell variants
> :bug: Add missing --eds_table__* css text color variables

- src/atoms/utils/date.test.ts
- src/atoms/utils/date.ts
- src/molecules/RichTextEditor/MenuBar/TextColor.test.tsx
- This PR fixes 'isBetweenDates' not working if passing in a string date
> :bug: Fix 'isBetweenDates' not working with string

- src/molecules/Select/Select.styles.ts
We have this issue in PWEX. Spacers are shrinking if not set min-width.
https://dev.azure.com/Equinor/DPP%20Upscaling%20of%20digital%20solutions/_boards/board/t/PWEX/Stories?System.AssignedTo=ARST%40equinor.com&workitem=568972
> 💄 Select menu child item spacing with multiline text issue

- src/molecules/FileProgress/FileProgress.stories.tsx
- src/molecules/FileProgress/RegularFileProgress.styles.tsx
- [AB#636916](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/636916)
---
- This PR fixes the FileProgress component not breaking really long words as expected, causing the icon to be squished
---
Before:
After:
> :bug: Fix really long filenames not working with FileProgress

- src/molecules/RichTextEditor/MenuBar/TextColor.test.tsx
- src/molecules/RichTextEditor/MenuBar/TextFormatting.test.tsx
- src/molecules/RichTextEditor/MenuBar/TextFormatting.tsx
Skipping bad rich text editor tests that kept failing. If we move to storybook test runner in the future maybe we can have these tests running again
> :white_check_mark: Skipping bad RTE tests

- package.json
- src/molecules/Select/Select.tsx
- src/molecules/Select/Select.types.ts
- src/molecules/Select/SingleSelect/SingleSelect.stories.tsx
- src/molecules/Select/SingleSelect/SingleSelect.test.tsx
- [AB#644200](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/644200)
---
- This PR adds the ability to have custom value component for single selects
> :sparkles: Added 'customValueComponent' prop to SingleSelect

- src/atoms/style/colors.ts
- src/atoms/style/darkTokens.ts
- src/atoms/style/lightTokens.ts
- src/providers/TutorialHighlightingProvider/TutorialPopover/StepIndicator.tsx
- [AB#647528](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/647528)
- [AB#648886](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/648886)
---
- This PR adds/fixes the colors for the stepper in a tutorial card
> :lipstick: New active/inactive tutorial step darkmode colors

- src/molecules/Select/Select.tsx
- [AB#657447](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/657447)
---
- This PR hides the placeholder/value elements in the Select components when loading=true
> :bug: Hide placeholder/values in Select components when loading=true

- src/organisms/TopBar/Account/ImpersonateMenu/UserImpersonation.tsx
- [AB#656882](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/656882)
- [AB#657445](https://dev.azure.com/Equinor/1f7078da-0ba3-4461-a220-c3e39c5c1f09/_workitems/edit/657445)
---
- This PR adds tooltips around truncated text in the impersonation menu
> :children_crossing: Add tooltips to impersonation user texts that might be truncated

- src/molecules/index.ts
This PR fixes some exports necessary for the IconCell component. The colors, variants and states are handled through a constant, which is now exported together with the types.
> :label: Fixed exports of const and types for IconCell colors, variants and states
